services:
  db:
    container_name: linkman-database
    hostname: linkman.main.db
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./main_db:/var/lib/mysql

    ports:
      - "3307:3306"
    networks:
      - linkman.net

  phpmyadmin:
    container_name: linkman-phpmyadmin
    image: phpmyadmin
    ports:
      - "8001:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306

    depends_on:
      - db
    networks:
      - linkman.net

  cache:
    container_name: linkman-cache
    image: redis
    ports:
      - '6379:6379'
    networks:
      - linkman.net

  localstack:
    container_name: local-sqs
    image: localstack/localstack:latest
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
    networks:
      - linkman.cloud

    healthcheck:
      test: [ "CMD", "awslocal","sqs", "list-queues" ]
      interval: 60s
      timeout: 5s
      retries: 3

  aws-cli:
    container_name: aws-cli-starter
    image: amazon/aws-cli
    depends_on:
        localstack:
          condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
    entrypoint: /bin/sh
    command: >
      -c "
      sleep 5;
      aws --endpoint-url=http://localstack:4566 sqs create-queue\
      --queue-name mail.fifo \
      --attributes FifoQueue=true;
      aws --endpoint-url=http://localstack:4566 sqs create-queue --queue-name metrics;
      echo 'queues created';
      "
    networks:
      - linkman.cloud


networks:
  linkman.net:
    driver: bridge
  linkman.cloud:
    driver: bridge