services:

  db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./main_db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - linkman.net

  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8000:80"
    environment:
      - PMA_ARBITRARY=1
    networks:
      - linkman.net

networks:
  linkman.net:
    driver: bridge